---
name: Variant_Calling_Somatic
description: Perform Variant calling on Somatic
authors:
  - Thibault Dayris
  - M boyba Diop
  - Marc Deloger
input:
  - Pairs of Tumor Fastq-formatted sequence files
  - Pairs of corresponding Non-Tumor Fastq-formatted sequence files
  - Cosmic database formatted as gzipped vcf and its tbi index (already provided for IGR Flamingo users)
  - dbSNP database formatted as gzipped vcf and its tbi index (already provided for IGR Flamingo users)
  - MSigDB database formatted as GMT (already provided for IGR Flamingo users)
  - GWASCatalog database formatted as TSV (already provided for IGR Flamingo users)
  - Kaviar database formatted as gzipped vcf and its tbi index (already provided for IGR Flamingo users)
  - SnpEff database downloaded with SnpEff itself (already provided for IGR Flamingo users)
  - CaptureKit genomic intervals formatted as BED (already provided for IGR Flamingo users)
  - Known variants from dbSNP, with only AF within the INFO field for GATK (already provided for IGR Flamingo users)
  - dbNSFP database formatted as TSV (already provided for IGR Flamingo users)
  - FastQ Screen databases (already provided for IGR Flamingo users)
output:
  - Annotated VCF files
  - MultiQC report
usage:
  - see https://github.com/tdayris/snakemake-wrappers/tree/Unofficial#somatic-wes