channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - r-xcell =1.3
  - r-mcpcounter =1.1.0
  - r-immunedeconv =2.1.1
  - r-epic =1.1
  - bioconductor-quantiseqr =1.6.0
  - r-mmcpcounter =1.1.0 
  - r-ggplot2 =3.4.2
  - r-dbplyr =2.3.1
  - r-tidyr =1.3.0
  - r-tibble =3.1.8
  - r-readr =2.4.1
  - r-rcolorbrewer =1.1_3