---
name: cibersort-abs
description: Use Cibersort Absolute to deconvolute gene expression onto cell types
authors:
  - Thibault Dayris
input:
  - expr_mat: Quantification table
  - cibersort_mat: Cibersort expression matrix, required in case Cibersort method is used.
  - cibersort_binary: Cibersort binary, required in case Cibersort method is used.
output:
  - rds: Path to RDS-formatted results
  - tsv: Path to TSV-formatted results
  - histogram: Histogram as described in official documentation
  - dotplot: Dotplots as described in official documentation
  - plotdir: Produce one dotplot per cell type in given directory
params:
  - method: The name of the method to use, see https://github.com/omnideconv/immunedeconv/blob/master/README.md#available-methods-licenses-citations
  - extra: Optional arguments for given method
  - 
