name: tximeta makeLinkedTxome
url: https://bioconductor.org/packages/release/bioc/vignettes/tximeta/inst/doc/tximeta.html
description: >
  makeLinkedTxome reads the checksum associated with a Salmon index at indexDir, and links it to key information about the transcriptome
author:
  - Thibault Dayris
input:
  - index_dir: Path to Salmon index
  - fasta: Path to the transcriptome sequence file (fasta formatted)
  - gtf: Path to the genome annotation file (GTF/GFF formatted)
output:
  - json: Path to the transcriptome checksum and metadata
params:
  - organism: Required. Name of the organism.
  - release: Required. Release number of the organism.
  - genome: Required. Genome version of the organism.
  - source: Required. Source of the genome.