name: agat_convert
description: >
  A single wrapper for all 10 agat conversion scripts.
url: https://agat.readthedocs.io/en/latest/index.html
author:
  - Thibault Dayris
input:
  - bed: Path to intervals (BED formatted) OR
  - embl: Path to sequences (EMBL or Uniprot formatted) OR
  - genscan: Path to genscan sequences (BED, Genscan or Fasta formatted) OR
  - mfannot: Path to genome annotation (MFannot formatted) OR
  - minimap2: Path to reads aligned by Minimap2 (SAM/BAM formatted) OR
  - gxf: Path to genome annotation (GFF/GTF/GXF formatted)
  - config: Optional path to agat config file
output:
  - Path to converted data, format acquired from file extension (GFF/GTF/ZFF/TSV formatted)
params:
  - extra: Optional parameters given to agat scripts besides IO.
  - script: Manually set script name instead of letting the wrapper decide by itself (in case of ambiguity)
notes: |
  Please read the official documentation in order to know which conversion are possible.

  Remember: Official documentation defines GXF as Gzip compressed GTF/GFF files.