name: agat_convert
description: >
  A single wrapper for all 10 agat conversion scripts.
url: https://agat.readthedocs.io/en/latest/index.html
author:
  - Thibault Dayris
input:
  - argname: Path to input file
output:
  - argname: Path to output file
params:
  - extra: Optional parameters given to agat scripts besides IO.
  - script: Script name (with or without extension)
notes: |
  Let `argname` be the command line argument, `-` or `--` are automatically added depending on argument size.

  Warning: when using `agat_convert_sp_gff2zff.pl` script, list the expected output file(s) in the same order as `--attribute` in `extra` parameter.