channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - multiqc =1.13
  - illumina-interop =1.1.28
  - multiqc_sav =0.0.3
  - illumina-utils =2.12
  - pip =22.2.2
  - pip:
    - interop==1.1.28