---
name: irods_copy
description: Perform simple iRODS copy
authors:
  - Thibault Dayris
input:
  - config: Path to a YAML file containing list of iRODS paths and destinations
output:
  - copied files
usage:
  - Do not run
