name: bcftools index
description: Index vcf/bcf file.
url: http://www.htslib.org/doc/bcftools.html#index
authors:
  - Jan Forster
  - Filipe G. Vieira
input:
  - Path to a VCF/BCF formatted file
output:
  - Path to the index file
params:
  extra: additional program arguments (not `--threads`, `-o/--output`, `--csi`, or `--tbi`)