channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - bioconductor-deseq2 =1.38.0
  - bioconductor-apeglm =1.20.0
  - bioconductor-ihw =1.26.0
  - r-ashr =2.2_54
  - bioconductor-biocparallel =1.32.5