name: deseq2
description: |
  Call differentially expressed genes with DESeq2
url: https://bioconductor.org/packages/3.16/bioc/html/DESeq2.html
authors:
  - Thibault Dayris
input:
  - se: Path to a summarized experiment object (RDS formatted) *OR*
  - txi: Path to a tximport/tximeta object (RDS formatted) *OR*
  - matrix: Path to a count matrix (CSV formatted)
output:
  - dds: Path to the DESeq Dataset object (RDS formatted)
parameters:
  - formula: Statistical formula (string) that will be used in the linear model
  - reference_level: The reference level for the studied factor (string, or list of strings)
  - tested_level: The tested level for the studied factor (string, or list of strings)
  - factor: The studied factor (string, or list of strings)