name: simpleaf add-chemistry
url: https://simpleaf.readthedocs.io/en/latest/add-chemistry-command.html
description: >
  Add a new custom chemistry to simpleaf’s registry of recognized chemistries.
author:
  - Thibault Dayris
output:
  - Path to the output `chemistry.json` file
params:
  - name: Name of the new custom chemistry
  - geometry: A custom geometry string to which you want to map this chemistry
note: |
  If you attempt to add a chemistry for a name that already exists in 
  the custom chemistry registry, the new geometry will overwrite the existing one.