name: pyroe make-spliced+intronic
url: https://pyroe.readthedocs.io/en/latest/building_splici_index.html#preparing-a-spliced-intronic-transcriptome-reference
description: >
  Build splici reference files for Alevin-fry. The splici index reference of a given species consists of the transcriptome of the species, i.e., the spliced transcripts and the intronic sequences of the species.
author:
  - Thibault Dayris
input:
  - gtf: Path to the genome annotation (GTF formatted)
  - fasta: Path to the genome sequence (Fasta formatted)
output:
  - to be commin
params:
  - read_length: The read length of the single-cell experiment being processed (determines flank size). Default is 100.
  - extra: Optional parameters to be passed to pyroe
