name: deepTools multiBigwigSummary
url: https://deeptools.readthedocs.io/en/develop/content/tools/multiBigwigSummary.html
description: >
  ``deepTools multiBigwigSummary`` computes the average scores for each of the files in every genomic region. 
  For more information about ``deepTools``, also see the `source code <https://github.com/deeptools/deepTools>`_.
authors:
  - Thibault Dayris
input:
  - bigwigs: Path to a list of bigwigs
  - blacklist: Optional path to blacklisted regions (BED)
  - bed: Optional path to regions to operate on (BED)
output:
  - npz: Path to output matrix
  - raw_counts: Optional path to uncompressed raw counts
note:
  - subcommand is inferred from input files
