name: simpleaf set-path
url: https://simpleaf.readthedocs.io/en/latest/set-paths.html
description: >
  set the paths to the relevant executables and store them in a configuration file in the `ALEVIN_FRY_HOME` directory.
author:
  - Thibault Dayris
input:
  salmon: Optional path to salmon
  piscem: Optional path to piscem
  alevin_fry: Optional path to alevin_fry
  pyroe: Optional path to pyroe
output:
  - Path to simpleaf cache file
params:
  - extra: Optional parameters passed to simpleaf set-path
note: |
  All simpleaf commands in a same `ALEVIN_FRY_HOME` directory. This directory is either defined 
  as an environment variable *before* running this wrapper, or provided a a parameter variable, 
  or set as output cache parent directory.

  It is advised to let the output name be `simpleaf_info.json`, but further wrappers will rename
  the cache data on-the-fly for simpleaf to function.