---
name: RNASeq
description: Perform various analyses on RNASeq-bulk
authors:
  - Thibault Dayris
input:
  - Fastq files
output:
  - DGE + Fusions + reports
usage:
  - see https://github.com/tdayris/snakemake-wrappers/tree/Unofficial#rna-seq-bulk
