name: tximeta
url: https://bioconductor.org/packages/release/bioc/vignettes/tximeta/inst/doc/tximeta.html
description: >
  Tximeta performs numerous annotation and metadata gathering tasks on behalf of users during the import of transcript quantifications from Salmon or alevin into R/Bioconductor.
author:
  - Thibault Dayris
input:
  - coldata: Path to the coldata file (TSV formatted). See notes for more information.
  - linked_txome: Path to the linked txome file (json formatted).
output:
  - txi: Path to the tximport SummarizedExperiment object.
params:
  - extra_tximeta: Optional parameters provided to both tximeta and tximport
note: |
  `tximeta` expects at least two columns in `coldata`:

    * `files` a pointer to the quant.sf files
    * `names` the unique names that should be used to identify samples
