name: Tximport DESeq2
url: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6178912.2/
description: >
  This meta-wrapper includes the following steps:

    +----------------------------+--------+--------------------------------------------------+
    | Step                       | Tool   | Reason                                           |
    +============================+========+==================================================+
    | Import                     | DEseq2 | Load SummarizedExperiment object and filter      |
    +----------------------------+----------+------------------------------------------------+
    | Differential Gene Analysis | DEseq2 | Call differentially expressed genes with DESeq2  |
    +----------------------------+--------+--------------------------------------------------+
authors:
  - Thibault Dayris
